---
-
  hosts: all
  vars:
    erlang_version: 17.1

  pre_tasks:
    -
      name: install packages
      sudo: yes
      apt: pkg={{ item }} state=installed
      with_items:
        - python-pycurl
        - python-software-properties

  roles:
    - { role: angstwad.docker_ubuntu, sudo: yes }
    - { role: Ansibles.erlang, sudo: yes }
    # - { role: zzet.rbenv, sudo: yes }

  tasks:
    -
      name: set locale
      sudo: yes
      lineinfile:
        dest=/etc/environment
        line='LC_ALL="en_US.UTF-8"'
        state=present
        backup=yes

    # -
    #   name: add repositories
    #   sudo: yes
    #   apt_repository: repo={{ item }}
    #   with_items:
    #     - "ppa:brightbox/ruby-ng"

    -
      name: apt-get update
      sudo: yes
      apt: update_cache=true cache_valid_time=3600

    -
      name: install packages
      sudo: yes
      apt: pkg={{ item }} state=installed
      with_items:
        - git
        - autoconf
        - curl
        - socat
        - libcap-dev

    # -
    #   name: install gems
    #   sudo: yes
    #   gem: name=rake state=present user_install=no

    -
      name: add docker group
      sudo: yes
      group: name=docker state=present
      tags: [docker]
    -
      name: add docker group to user
      sudo: yes
      user: name=vagrant append=yes groups=docker
      notify: "Start Docker"
      tags: [docker]
    -
      name: install starter docker image
      shell: docker pull mokevnin/starter
      tags: [docker]

    -
      name: download erlang-history
      git: repo=https://github.com/ferd/erlang-history.git
        dest=/var/tmp/erlang-history
      tags: [erlang]
    -
      name: make erlang-history
      shell: cd /var/tmp/erlang-history && make
      tags: [erlang]
    -
      name: install erlang-history
      shell: cd /var/tmp/erlang-history && sudo make install
      tags: [erlang]
